---
- name: create instance through ansible
  hosts: localhost
  become: yes
  tasks:
  - name: launch instance
    ec2:
     key_name: pratice
     instance_type: t2.micro
     image: ami-0e2005b9ade448037
     region: us-east-2
     wait: yes
     group: security-default
     instance_tags:
        Name: dynamic-servers
     count: 2
     vpc_subnet_id: subnet-24b43d68
     assign_public_ip: yes
