---
- name: install apache on dynamic servers
  hosts: tag_Name_dynamic_servers
  become: yes
  tasks:
  - name: install apache
    apt:
     name: apache2
     state: present


  - name: start the webserver
    service:
     name: apache2
     state: started   