---
- name: Install apache on ubuntu server
  hosts: webservers
  become: yes
  tasks:
  - name: updating the repos
    apt:
      name: "*"
      state: latest
  - name: install apache
    apt:
      name: apache2
      state: present

  - name: copy the index to server
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restart

  handlers:
  - name: restart
    service:
      name: apache2
      state: restarted    