---
- name: Build docker image from Dockerfile
  hosts: webservers
  become: yes
  tasks:


  - name: Install python-docker  on Debian based distribution
    apt: 
      name: python-docker
      update_cache: yes
    when: ansible_os_family == 'Debian'  

  - name: Move the war file to node side
    copy: 
      src: naglogin-1.0.war
      dest: /root

  - name: Build docker image
    copy:
      src: Dockerfile
      dest: /root


  - name: Build Docker image from Dockerfile
    docker_image:
      name: web
      path: /root
      state: build

  - name: Log into DockerHub
    docker_login:
     username: nagendra464
     password: loveudarling    

  - name: Create Container
    docker_container:
      name: tomcat
      image: web:latest
      ports:
        - 8090:8080
      privileged: true   
  
    