---
- name: install httpd on redhat server
  hosts: webservers
  become: yes
  tasks:
  - name: install webservers
    yum:
      name: httpd
      state: present

  - name: To start the service
    service:
      name: httpd
      state: started