---
- name: install httpd on redhat server
  hosts: webservers
  become: yes
  tasks:
  - name: install webservers
    yum:
      name: httpd
      state: present

  - name: To start the service
    service:
      name: httpd
      state: started

  - name: To copy index file to apache server
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restart
    
    
  handlers:
  - name: restart
    service:
      name: httpd
      state: restarted  
      
