---
# tasks file for tomcat
- include_tasks: install-java.yml
- include_tasks: create-tomcatuser.yml
- include_tasks: install-tomcat.yml
- include_tasks: update-permissions.yml
- include_tasks: service.yml
- include_tasks: deamon-reload.yml
- include_tasks: user.yml
- include_tasks: manager-host.yml