---
- name: update the permissions
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    group: tomcat

- name: tomcat group read access to the conf directory
  file:
    path: /opt/tomcat/conf
    state: directory
    recurse: yes
    mode: g+r,g+x   