---
- name: update the permissions
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    group: tomcat

- name: tomcat group read access to the conf directory
  file:
    path: /opt/tomcat/conf
    state: directory
    recurse: yes
    mode: g+r,g+x   

- name: tomcat user the owner of the webapps, work, temp, and logs
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: tomcat  